### PR TITLE
update : added login and SignUp pages. working fine with sharedPrefrences.

### PR DESCRIPTION
**Pull request by nycanshu**
Sign Up page
image

Login Page

image

### CODE REVIEW

**Comment by nycanshu** [comment]
Please accept his contribution under HacktoberFest24.

**Comment by dhyey2075** [comment]
You have done almost everything correctly. But when we are on the home page we get an option of back that should not be available because it redirects user to login or sign up again which logouts the user. Try to fix this.
Also handle the case of overflow as in my device it is overflowing.
image

image

**Comment by nycanshu** [comment]
I am glad that you are happy with my contribution.

Please accept this contribution and create a new issue. And assign it please.🙏🏻

This help me a lot to start my valid contribution in Hacktobarfest24.

**Comment by 10maysingh** [comment]
Please refer to this previous comment that @dhyey2075 made on your sign up page. The page is overflowing, so please fix that. Until that we cannot count this as a contribution. Please complete this by the end of today. If you are unable to complete this, we will need to reassign the issue.

> You have done almost everything correctly. But when we are on the home page we get an option of back that should not be available because it redirects user to login or sign up again which logouts the user. Try to fix this. Also handle the case of overflow as in my device it is overflowing. image
> 
> image

**Comment by nycanshu** [comment]
Updated all mentioned points. Verify and let me know.

**Comment by dhyey2075** [comment]
1) When I created the account and login and again open the app it is asking for login again this makes the UX bad.
2) I am also able to make the account with same email multiple times.

https://github.com/user-attachments/assets/c79adbb3-50a6-4f69-a91e-b067b5e6d21c

**Comment by nycanshu** [comment]
Mmmm... Nice observation. 

Ohh its just slip out of my mind to check this. No issue I will fix it too. It's just two line of modification in Main.dart and one line of modification in shared preferences.

**Comment by nycanshu** [comment]
Updated required changes. Verify it once

**Comment by dhyey2075** [comment]
When I reopen the app after login it is crashed. Fix this issue.

https://github.com/user-attachments/assets/89b8aabc-deaa-495b-ad4d-2739313eec69

**Comment by dhyey2075** [comment]
You should display the name and details on the home page and the profile page also.
Also the issue which I previously mentioned that an account with similar email is also able to make.

**Comment by 10maysingh** [comment]
I think you haven't met with our requirements so we are reassigning this issue to someone else.

**Pull request closed without merging**
