### PR TITLE
Add native splash screen

### LINKED ISSUE #3: Design a Splash screen
- Design a captivating splash screen: Create a visually appealing, branded image or animation to enhance the app's loading experience.
- Implement splash screen logic: Display the splash screen upon app launch and ensure proper functionality.
- Configure screen duration: Set the splash screen's display time to provide a smooth transition to the main app interface.

### PR DESCRIPTION
**Pull request by iPriyanshu19**
# Pull Request: Issue #3 - Splash Screen Implementation

## Summary

This pull request addresses Issue #3 by designing and implementing a captivating splash screen for our application. The enhancements made include a visually appealing design, the necessary logic to display the splash screen upon app launch, and configuration of the display duration for a smooth transition to the main app interface.

## Changes Made

1. **Splash Screen Design:**
   - Created a visually appealing splash screen image/animation that reflects our brand identity.
   - Ensured that the design is responsive and looks great on various screen sizes.

2. **Splash Screen Logic Implementation:**
   - Added the logic to display the splash screen immediately upon app launch.
   - Implemented the necessary code to manage the transition from the splash screen to the main application interface.

3. **Configuration of Screen Duration:**
   - Set the splash screen display time to provide a seamless user experience.
   - Included functionality to allow for easy adjustments of the display time in the future.

## Testing

- Verified that the splash screen displays correctly on launch.
- Ensured that the transition to the main app interface is smooth and occurs after the configured duration.
- Tested on multiple devices and screen sizes to confirm responsive design.

## Screenshots

Splash screen

## Related Issues

- Closes #3

### CODE REVIEW

**Comment by dhyey2075** [comment]
https://github.com/user-attachments/assets/8b2a0e26-6eb5-45ff-8f93-c95731ec61c4

This can be seen on my device.
No problem we are giving you one more day to fix this.
Make it such that it looks the same on all devices.

**Comment by iPriyanshu19** [comment]
which android version is running on your phone?

**Comment by dhyey2075** [comment]
> which android version is running on your phone? check out in some other device if you have access to.

I have android 14. And no matter what is the android version when we build the app it should be same in all android devices. But I will try in older android version if I could find it. Otherwise you have done everything else correctly. But try to solve this issue also.

**Comment by iPriyanshu19** [comment]
I am not able to trace the issue. The current splash screen is working fine in other devices with old android version. U can merge and raise a issue for bug fixing if you want.


Add hacktoberfest labels to the merge request.
@dhyey2075

**Pull request closed without merging**
