### PR TITLE
frotend for profile page

### PR DESCRIPTION
**Pull request by prxjwal**
profile

### CODE REVIEW

**Comment by dhyey2075** [comment]
You do not need to show activity track on the profile page instead you need to show:
My Profile
Login/SignUp
Edit Profile
Share my progress
Current streak, joined date, etc.
this types of items on profile page. So make it that way!

**Comment by prxjwal** [comment]
d
lmk if u need changes

**Comment by dhyey2075** [comment]
Ok your pull request has been merged!

**Comment by prxjwal** [comment]
pr was  excluded from hacktobest, u should put hacktoberfesr-acepted badge

**Pull request merged**
